# syntax=docker.io/docker/dockerfile:1

FROM node:18-alpine AS base

WORKDIR /app

ARG USER_ID=1000
ARG GROUP_ID=1000

# Detect and create only if needed
RUN if ! getent passwd ${USER_ID} >/dev/null; then \
      addgroup -g ${GROUP_ID} nodejs && \
      adduser -D -u ${USER_ID} -G nodejs nextjs; \
    else \
      echo "User with UID ${USER_ID} already exists. Skipping creation."; \
    fi

RUN chown -R ${USER_ID}:${GROUP_ID} /app
USER ${USER_ID}

# Install dependencies only
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi

FROM base AS nextjs
EXPOSE 3000

FROM base AS wsserver
EXPOSE 3001
