name: dataflow
services:
  traefik:
    image: traefik:v2.10
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"
    networks:
      - dataflow

  nats:
    labels:
      - "traefik.enable=false"
    image: nats:latest
    ports:
      - "4222:4222"   # Main client connections
      - "8222:8222"   # Monitoring endpoint
    restart: unless-stopped
    networks:
      - dataflow

  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.docker.network=dataflow"
    build:
      context: ..
    networks:
      - dataflow
    depends_on:
      - traefik

  ws-gateway:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ws-gateway.entrypoints=web"
      - "traefik.http.routers.ws-gateway.service=ws-gateway"
      - "traefik.http.services.ws-gateway.loadbalancer.server.port=3001"
      - "traefik.docker.network=dataflow"
    build:
      context: ..
    networks:
      - dataflow
    depends_on:
      - traefik
      - nats
  
  runner:
    labels:
      - "traefik.enable=false"
    build:
      context: ..
    networks:
      - dataflow
    depends_on:
      - nats

networks:
  dataflow:
    name: dataflow
