services:
  traefik:
    volumes:
      - ./traefik/dynamic.dev.yml:/etc/traefik/dynamic.yml:ro
      - ../certs:/etc/certs:ro

  mongo-express:
    labels:
      - "traefik.http.routers.mongo-express.entrypoints=websecure"
      - "traefik.http.routers.mongo-express.tls=true"

  frontend:
    labels:
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
    env_file:
      - .env.docker.tls.local

  ws-gateway:
    labels:
      - "traefik.http.routers.ws-gateway.entrypoints=websecure"
      - "traefik.http.routers.ws-gateway.tls=true"
