services:
  traefik:
    labels:
      # - "traefik.http.routers.dashboard.rule=Host(`traefik.dataflow-ide.dev`)"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
    restart: always

  frontend:
    labels:
      # - "traefik.http.routers.frontend.rule=Host(`dataflow-ide.dev`)"
      - "traefik.http.routers.frontend.rule=Host(`dataflow-ide.local`)"
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - ../apps/frontend/.env.production
    build:
      dockerfile: docker/Dockerfile.prod
      target: runner
  
  ws-gateway:
    labels:
      # - "traefik.http.routers.ws-gateway.rule=Host(`ws.dataflow-ide.dev`) && PathPrefix(`/ws`)"
      - "traefik.http.routers.ws-gateway.rule=Host(`ws.dataflow-ide.local`) && PathPrefix(`/ws`)"
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - ../apps/frontend/.env.production
    build:
      dockerfile: docker/Dockerfile.prod
      target: wsserver
