services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
      - "--providers.docker.network=dataflow"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"
    networks:
      - dataflow

  nextjs:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.next.entrypoints=web"
      - "traefik.http.services.next.loadbalancer.server.port=3000"
      - "traefik.docker.network=dataflow"
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
      target: runner
    env_file:
      - ../.env.production
    environment:
      - NODE_ENV=production
    networks:
      - dataflow
    depends_on:
      - traefik

  ws-server:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ws-server.entrypoints=web"
      - "traefik.http.routers.ws-server.service=ws-server"
      - "traefik.http.services.ws-server.loadbalancer.server.port=3001"
      - "traefik.docker.network=dataflow"
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
      target: wsserver
    env_file:
      - ../.env.production
    environment:
      - NODE_ENV=production
    networks:
      - dataflow
    depends_on:
      - traefik

networks:
  dataflow:
    name: dataflow
