services:
  traefik:
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`traefik.dataflow-ide.dev`)"
      # - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
    restart: always
    volumes:
      - ./traefik/traefik.prod.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.prod.yml:/etc/traefik/dynamic.yml:ro
      # - ../certs:/etc/certs:ro
      - ./traefik/acme.json:/etc/traefik/acme.json

  nats:
    restart: always
  
  mongodb:
    env_file:
      - ../apps/frontend/.env.production
    restart: always
  
  mongo-express:
    labels:
      - "traefik.http.routers.mongo-express.rule=Host(`me.dataflow-ide.dev`)"
      - "traefik.http.routers.mongo-express.middlewares=secure-headers@file"
      - "traefik.http.routers.mongo-express.entrypoints=websecure"
      - "traefik.http.routers.mongo-express.tls=true"
      - "traefik.http.routers.mongo-express.tls.certresolver=letsencrypt"
    env_file:
      - ../apps/frontend/.env.production
    restart: always

  frontend:
    labels:
      - "traefik.http.routers.frontend.rule=Host(`dataflow-ide.dev`)"
      # - "traefik.http.routers.frontend.rule=Host(`dataflow-ide.local`)"
      - "traefik.http.routers.frontend.middlewares=secure-headers@file"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - ../apps/frontend/.env.production
    build:
      dockerfile: docker/Dockerfile.prod
      target: frontend
  
  ws-gateway:
    labels:
      - "traefik.http.routers.ws-gateway.rule=Host(`ws.dataflow-ide.dev`)"
      # - "traefik.http.routers.ws-gateway.rule=Host(`ws.dataflow-ide.local`)"
      - "traefik.http.services.ws-gateway.loadbalancer.sticky.cookie.name=ws_sticky"
      - "traefik.http.routers.ws-gateway.middlewares=secure-headers@file"
      - "traefik.http.routers.ws-gateway.entrypoints=websecure"
      - "traefik.http.routers.ws-gateway.tls=true"
      - "traefik.http.routers.ws-gateway.tls.certresolver=letsencrypt"
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - ../apps/ws-gateway/.env.production
    build:
      dockerfile: docker/Dockerfile.prod
      target: ws-gateway

  runner:
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - ../apps/runner/.env.production
    build:
      dockerfile: docker/Dockerfile.prod
      target: runner
